## Упражнения по библиотеке Numpy

In [2]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [3]:
# создаём случайный массив
rand_array = np.random.randint(0, 10, 10)
mask = (rand_array > 3) & (rand_array < 8)
rand_array[mask] *= -1
print(rand_array)

[ 3  3  3  2 -7 -5  2 -4 -4 -4]


**2.** Заменить максимальный элемент случайного массива на 0

In [4]:
# your cod
rand_array = np.random.randint(0, 10, 10)
print(rand_array)
max_index = np.argmax(rand_array)
rand_array[max_index] = 0
rand_array

[3 9 4 5 3 2 6 5 0 8]


array([3, 0, 4, 5, 3, 2, 6, 5, 0, 8])

**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив



In [5]:
# your code
array_1 = [1, 2, 3]
array_2 = [4, 5, 6]


array_3 = np.kron(array_1, array_2)
# Преобраз в матрицу 
array_3 = array_3.reshape(len(array_1), len(array_2))
array_3

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [6]:
# Массив A
A = np.random.randint(0, 10, (8, 3))
print(A, '\n')
# Массив B 
B = np.random.randint(0, 10, (2, 2))
print(B, '\n')

sets_B = [set(i) for i in B]
print(sets_B, '\n')

result = []
for row_A in A:
    set_A = set(row_A)
    if all(set_B.issubset(set_A) for set_B in sets_B):
        result.append(row_A)

result = np.array(result)


[[2 4 6]
 [8 9 3]
 [1 8 4]
 [1 5 0]
 [6 8 8]
 [1 0 4]
 [9 7 4]
 [7 1 9]] 

[[0 1]
 [8 2]] 

[{0, 1}, {8, 2}] 



**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [7]:
# your code
set = np.random.randint(0, 2, (10, 3))
print(set, '\n')
# Находим строки с неравными значениями
set_2 = np.array([i for i in set if len(np.unique(i)) > 1])
print(set_2)

[[0 1 0]
 [1 1 1]
 [1 0 0]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [0 0 0]
 [1 1 1]
 [1 0 1]] 

[[0 1 0]
 [1 0 0]
 [1 0 1]
 [0 1 0]
 [1 0 0]
 [0 1 0]
 [1 0 1]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [8]:
# your code
set = np.array([
    [2, 4, 6],
    [1, 1, 1],
    [2, 5, 3],
    [1, 1, 1],
    [5, 3, 2],
    [1, 1, 1]
    
])
print(set, '\n')

un_rows, un_ind = np.unique(set, axis=0, return_index=True)
un_set = set[np.sort(un_ind)]
print(un_set)

[[2 4 6]
 [1 1 1]
 [2 5 3]
 [1 1 1]
 [5 3 2]
 [1 1 1]] 

[[2 4 6]
 [1 1 1]
 [2 5 3]
 [5 3 2]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [9]:
# NoNumpy
def product_non_zero_diagonal(matrix):
    product = 1
    min_dim = min(len(matrix), len(matrix[0]))
    for i in range(min_dim):
        if matrix[i][i] != 0:
            product *= matrix[i][i]
    return product

# Пример использования
matrix = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
result = product_non_zero_diagonal(matrix)
print(result)

3


In [10]:
# Numpy
def product_non_zero_diagonal_numpy(matrix):
    diagonal_elements = np.diag(matrix)
    non_zero_diagonal_elements = diagonal_elements[diagonal_elements != 0]
    product = np.prod(non_zero_diagonal_elements)
    return product

# Пример использования
matrix = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
result = product_non_zero_diagonal_numpy(matrix)
print(result) 

3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [11]:
#NoNumpy
def are_multisets_equal(x, y):
    return sorted(x) == sorted(y)

# Пример использования
x = [1, 2, 2, 4]
y = [4, 2, 1, 2]
result = are_multisets_equal(x, y)
print(result)  

True


In [12]:
# Numpy
def are_multisets_equal_numpy(x, y):
    return np.array_equal(np.sort(x), np.sort(y))

# Пример использования
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])
result = are_multisets_equal_numpy(x, y)
print(result)

True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [13]:
# NoNumpy
def max_after_zero(x):
    max_value = float('-inf')
    found_zero = False

    for elem in x:
        if found_zero:
            max_value = max(max_value, elem)
            found_zero = False
        elif elem == 0:
            found_zero = True

    return max_value

# Пример использования
x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
result = max_after_zero(x)
print(result)

3


In [14]:
# Numpy
def max_after_zero_numpy(x):
    zeros = np.where(x == 0)[0]
    if len(zeros) == 0:
        return None

    # Индексы элементов после нулей
    next_indices = zeros + 1

    # Исключаем нули, которые находятся в конце
    next_indices = next_indices[next_indices < len(x)]

    # Находим максимальный элемент после нуля
    max_value = np.max(x[next_indices])

    return max_value

# Пример использования
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
result = max_after_zero_numpy(x)
print(result)

5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [15]:
def run_length_encoding(x):
    if not x:
        return ([], [])

    numbers = [x[0]]
    counts = [1]

    for i in range(1, len(x)):
        if x[i] == x[i - 1]:
            counts[-1] += 1
        else:
            numbers.append(x[i])
            counts.append(1)

    return (numbers, counts)

# Пример использования
x = [2, 2, 2, 3, 3, 3, 5]
result = run_length_encoding(x)
print(result)


([2, 3, 5], [3, 3, 1])


In [16]:
# Numpy
def run_length_encoding_numpy(x):
    if len(x) == 0:
        return (np.array([]), np.array([]))

    # Индексы, где меняется элемент
    change_indices = np.where(x[:-1] != x[1:])[0]

    # Найдем числа и их количество
    numbers = x[change_indices]
    counts = np.diff(np.concatenate(([change_indices[0] + 1], change_indices + 2)))

    return (numbers, counts)

# Пример использования
x = np.array([2, 2, 2, 3, 3, 3, 5])
result = run_length_encoding_numpy(x)
print(result)

(array([2, 3]), array([1, 3], dtype=int64))


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [20]:
# Numpy 
def euclidean_distance_matrix(X, Y):
    # Вычисление квадрата Евклидова расстояния между каждой парой объектов
    distances_sq = np.sum(X**2, axis=1, keepdims=True) + np.sum(Y**2, axis=1) - 2*np.dot(X, Y.T)
    # Обработка отрицательных нулевых расстояний из-за ошибок округления
    distances_sq[distances_sq < 0] = 0
    # Вычисление Евклидовых расстояний
    distances = np.sqrt(distances_sq)
    return distances

# Пример использования
X = np.array([[1, 2], [4, 5], [7, 8]])
Y = np.array([[2, 3], [5, 6]])
result_numpy = euclidean_distance_matrix(X, Y)
print("Евклидовы расстояния (NumPy):")
print(result_numpy)

Евклидовы расстояния (NumPy):
[[1.41421356 5.65685425]
 [2.82842712 1.41421356]
 [7.07106781 2.82842712]]


In [21]:
# scipy.spatial.distance.cdist
from scipy.spatial.distance import cdist
import time

# Генерация случайных выборок X и Y
np.random.seed(0)
X = np.random.rand(1000, 100)
Y = np.random.rand(500, 100)

# Вычисление матрицы Евклидовых расстояний с использованием NumPy
start_time = time.time()
result_numpy = euclidean_distance_matrix(X, Y)
numpy_execution_time = time.time() - start_time

# Вычисление матрицы Евклидовых расстояний с использованием cdist
start_time = time.time()
result_cdist = cdist(X, Y)
cdist_execution_time = time.time() - start_time

print("Время выполнения (NumPy):", numpy_execution_time)
print("Время выполнения (cdist):", cdist_execution_time)

# Проверка корректности результатов
print("Результаты совпадают:", np.allclose(result_numpy, result_cdist))


Время выполнения (NumPy): 1.6297791004180908
Время выполнения (cdist): 0.05544734001159668
Результаты совпадают: True


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [22]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [31]:
calorie_stats = np.loadtxt("D:\\GitHub\\Task_2_Numpy_Pandas\\cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [67]:
Crunchie_Munchies_cal = 60
average_calories = np.average(calorie_stats)
average_calories


106.88311688311688

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [68]:
calorie_stats_sorted = np.sort(calorie_stats)
calorie_stats_sorted

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [74]:
median_calories = np.median(calorie_stats_sorted)
median_calories

110.0

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [79]:
# Проценнтиль(начинаем с 0)
perc = 0
# Ищем наименший процентиль, превышающий 60 калл
while True:
    nth_percentile = np.percentile(calorie_stats, perc)
    if nth_percentile > 60:
        break
    perc += 1

nth_percentile

70.0

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [83]:
# процент хлопьев с более чем 60 кал
more_calories = np.sum(calorie_stats > 60) / len(calorie_stats) * 100
print(more_calories, '%')

96.1038961038961 %


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [86]:
calorie_std = np.std(calorie_stats)
calorie_std

19.35718533390827

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [87]:
# your code